include:
  # corne
  # - board: nice_nano_v2
  #   shield: corne_central_left
  #   artifact-name: corne_central_left
  - board: nice_nano_v2
    shield: corne_right 
    artifact-name: corne_right
  - board: nice_nano_v2
    shield: corne_left 
    artifact-name: corne_left
  - board: nice_nano_v2
    shield: corne_dongle
    artifact-name: corne_dongle
  # reset
  # - board: seeeduino_xiao_ble
    # shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: corne_reset